### ISSUE TITLE
Usage on lighthouse 5?

### ISSUE THREAD

**Issue by YoranBosman** [brightalley/lighthouse-apollo#4]
I'd love to try this package but it doesn't seem to support lighthouse 5 yet?

 - bright-alley/lighthouse-apollo[v1.5, ..., v1.5.2] require nuwave/lighthouse ^v4 -> found nuwave/lighthouse[v4.0.0, ..., v4.18.0] but it conflicts with your root composer.json require (^5)

**Comment by YoranBosman** [comment]
i see, master branch does support it

**Comment by MaartenStaa** [comment]
@YoranBosman That's correct. At the moment, we're still running Lighthouse v4 in production. Actually later this week I'm working on upgrading to version 5, so part of that will be making any more necessary upgrades to this package, and tagging a 2.0 release.

**Comment by pyrou** [comment]
Can't you just merge 1.x into master like previous release to get recent optim/fix on redis on lighthouse 5 ?
