### ISSUE TITLE
GraphQL Subscriptions?

### ISSUE THREAD

**Issue by hncvj** [brightalley/lighthouse-apollo#5]
Hi, can we use this for graphql subscriptions?

**Comment by MaartenStaa** [comment]
Hi @hncvj, we just recently started using subscriptions, so I just tested this for you. The tracings for subscriptions are tracked and sent just like queries and mutations, as they follow the same process within Lighthouse (i.e. the same events are fired that this package listens to). 

The only thing that wasn't working yet, is that the query signature wasn't taking subscriptions into account, I have just published a new version of this package to correct that.
