### ISSUE TITLE
Should this package be referenced in Lighthouse docs?

### ISSUE THREAD

**Issue by spawnia** [brightalley/lighthouse-apollo#7]
Hi, do you want this package referenced in https://lighthouse-php.com/resources/#plugins?

**Comment by MaartenStaa** [comment]
Hi @spawnia, I think listing this package on the Lighthouse website may be useful. I don't know how many Lighthouse users also use Apollo Studio, but when you do, this package adds a lot of value, I think.

So yes, please reference this package on the Lighthouse plugins page.
